### ISSUE TITLE
Make new database for attendance system 

### ISSUE THREAD

**Issue by ghost** [timstephens/Dorbot#6]
hello,
In the bingeing thanks for your project and explanation.
I want to make new database that take the user info after validation condition be true from userAllowedIn() function .
how to connect this new database to my raspberry pi and put info in it?
What is the role of userRecord() function at dorbot_server.cpp?
I hope that you can help me in my project.
Thank you

**Comment by timstephens** [comment]
> What is the role of userRecord() function at dorbot_server.cpp?

This is to write a log of who swiped the card into the system. It takes the card ID, and the result of userAllowedIn() and writes them to the table called 'access'.

Best,
Tim
